server:
  port: 8308
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: dev


logging:
  level:
    com.ssafy.mongttang: debug


